services:
  - type: web
    name: shoutcode
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    plan: free
    envVars:
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
